name: salary_calculator
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/CustomFont.ttf  # Add this line to include the font file in the assets

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont.ttf
