name: iOS Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: write  # Allows GITHUB_TOKEN to upload releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Run flutter build ios
        run: flutter build ios --release --no-codesign

      - name: Create .ipa file
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r FlutterIpaExport.ipa Payload

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: FlutterIpaExport.ipa
          tag: latest
